# Generated by Django 3.1.1 on 2020-09-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_qr_code', models.URLField(null=True)),
                ('thumbnail_url', models.URLField(null=True)),
                ('agency_zip', models.CharField(max_length=200, null=True)),
                ('agency_address', models.CharField(max_length=200, null=True)),
                ('agency_state', models.CharField(max_length=200, null=True)),
                ('agency_city', models.CharField(max_length=200, null=True)),
                ('agency_name', models.CharField(max_length=200, null=True)),
                ('circumstances', models.TextField(blank=True, null=True)),
                ('eye_color', models.CharField(max_length=200, null=True)),
                ('hair_color', models.CharField(max_length=200, null=True)),
                ('ethnicity', models.CharField(max_length=200, null=True)),
                ('weight', models.CharField(max_length=200, null=True)),
                ('height', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('age_when_missing', models.CharField(max_length=200, null=True)),
                ('current_age', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('id_number', models.CharField(max_length=200, null=True, unique=True)),
                ('date_reported', models.CharField(max_length=200, null=True)),
                ('agency_website', models.URLField(null=True)),
            ],
        ),
    ]
