# Generated by Django 3.1 on 2020-09-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('l_name', models.CharField(max_length=200)),
                ('age_when_missing', models.IntegerField()),
                ('age_now', models.IntegerField()),
                ('image_url', models.URLField()),
                ('date_last_seen', models.CharField(max_length=100)),
                ('city_last_seen', models.CharField(max_length=200)),
                ('agency_phone', models.CharField(max_length=200)),
                ('agency_web', models.URLField()),
            ],
        ),
    ]
