# Generated by Django 3.1.1 on 2020-09-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='agency_website',
            field=models.URLField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='case_qr_code',
            field=models.URLField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='thumbnail_url',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
