# Generated by Django 3.1.1 on 2020-09-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20200914_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='age_when_missing',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='agency_address',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='agency_city',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='agency_name',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='agency_state',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='agency_website',
            field=models.URLField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='agency_zip',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='case_qr_code',
            field=models.URLField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='circumstances',
            field=models.CharField(max_length=10000000, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='current_age',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='date_reported',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='ethnicity',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='eye_color',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='first_name',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='hair_color',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='height',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='id_number',
            field=models.CharField(max_length=2000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='last_name',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='thumbnail_url',
            field=models.URLField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='weight',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
