# Generated by Django 3.1.1 on 2020-09-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20200906_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='date_reported',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
