# Generated by Django 3.1.1 on 2020-09-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_missingperson_date_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='agency_website',
            field=models.URLField(null=True),
        ),
    ]
